volumes:
  db-data:
  static:

services:
  postgres-db:
    image: postgres:17.1
    env_file:
      - ./backend/MTSSummarizerBackend/.env
    volumes:
      - db-data:/var/lib/postgresql/data

  mts-summarizer:
    build: ./backend/MTSSummarizerBackend/
    env_file:
      - ./backend/MTSSummarizerBackend/.env
    depends_on:
      - postgres-db
    volumes:
      - static:/backend_static

  sentiment-analyzer-model-api:
    build: ./backend/SentimentAnalyzerModelAPI/

  comments-clustering-model-api:
    build: ./backend/CommentClusteringModelAPI/

  frontend:
    build: ./frontend/
    volumes:
      - static:/frontend/build

  gateway:
    build: ./gateway/
    ports:
      - 80:80
    volumes:
      - static:/staticfiles
    depends_on:
      - mts-summarizer
      - sentiment-analyzer-model-api
      - comments-clustering-model-api
      - frontend