# Generated by Django 5.2 on 2025-05-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-created_at',), 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='summary',
        ),
        migrations.AddField(
            model_name='article',
            name='article_summary',
            field=models.TextField(default='', verbose_name='Резюме статьи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='comments_summary',
            field=models.TextField(default='', verbose_name='Резюме комментариев'),
            preserve_default=False,
        ),
    ]
